name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '📚 Documentation'
    labels:
      - 'chore'
      - 'docs'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  $CHANGES