name: 🐛 Flashing Issue
description: Report a problem during device flashing
title: "[Flash] "
labels: ["bug", "flashing"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a flashing issue!
        
  - type: dropdown
    id: chip-family
    attributes:
      label: Chip Family
      description: Select your device chip family
      options:
        - TI CCXX52 (CC2652, CC1352, CC2538)
        - Silabs EFR32
        - TI CC25XX (CC2530, CC2531 and so on)
        - Arduino
        - ESP8266 / ESP32
        - Other
    validations:
      required: true
      
  - type: input
    id: device-model
    attributes:
      label: Device Model
      description: Specific model (e.g., ZigStar UZG-01, SONOFF ZBDongle-E, Arduino Uno)
    validations:
      required: true
      
  - type: dropdown
    id: connection-type
    attributes:
      label: Connection Type
      options:
        - Local USB
        - Remote via Bridge
        - CC Debugger
        - CC Loader
    validations:
      required: true
      
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Browser name and version
      placeholder: ex. Chrome 120
    validations:
      required: true
      
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: ex. Windows 11, macOS 14, Ubuntu 22.04
    validations:
      required: true
      
  - type: dropdown
    id: firmware-source
    attributes:
      label: Firmware Source
      options:
        - Local file
        - Cloud repository
      
  - type: input
    id: firmware-file
    attributes:
      label: Firmware File
      description: Filename or cloud firmware selection
      
  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: Describe what happened during flashing
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Console Logs
      description: Please copy logs from the tool (disable "Show TX/RX")
      render: shell
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information
