---
name: 🌉 Bridge Issue
about: Report a problem with the bridge application
title: '[Bridge] '
labels: ['bug', 'bridge']
assignees: []
---

## Bridge Information
- **Bridge Version**: (e.g., v0.3.2)
- **Installation Method**: (Standalone / Docker / Home Assistant Add-on)
- **OS/Platform**: (e.g., Windows, macOS, Linux, Raspberry Pi, HA OS)
- **Architecture**: (e.g., amd64, arm64, armv7)

## Network Setup
- **Bridge Address**: (e.g., http://192.168.1.100:8765)
- **Access Type**: (Local network / Same machine)
- **Firewall/Antivirus**: (Yes/No, which one?)

## Problem Description
<!-- Describe what's wrong with the bridge -->

## Steps to Reproduce
1. 
2. 
3. 

## Expected Behavior
<!-- What should have happened? -->

## Actual Behavior
<!-- What actually happened? -->

## Bridge Logs
<!-- Please provide bridge console output or logs -->
```
Paste bridge logs here
```

## Additional Context
<!-- Add configuration files (remove sensitive data), screenshots, or other info -->
