---
name: 💡 Feature Request / Improvement
about: Suggest an idea or improvement for the Multi-Tool
title: '[Idea] '
labels: ['enhancement']
assignees: []
---

## Feature Category
<!-- Check what area this relates to -->
- [ ] User Interface
- [ ] Flashing/Programming
- [ ] Bridge
- [ ] Device Support
- [ ] Firmware Management
- [ ] Documentation
- [ ] Other

## Problem or Need
<!-- Is your feature request related to a problem? Describe it -->

## Proposed Solution
<!-- Describe your idea or suggestion -->

## Alternative Solutions
<!-- Have you considered any alternative approaches? -->

## Use Case
<!-- How would this feature be used? Who would benefit? -->

## Additional Context
<!-- Add mockups, screenshots, links, or other relevant information -->
