name: 💡 Feature Request / Improvement
description: Suggest an idea or improvement for the Multi-Tool
title: "[Idea] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!
        
  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this relate to?
      options:
        - User Interface
        - Flashing/Programming
        - Bridge
        - Device Support
        - Firmware Management
        - Documentation
        - Other
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem or Need
      description: Is your feature request related to a problem? Describe it
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your idea or suggestion
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      
  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: How would this feature be used? Who would benefit?
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add mockups, screenshots, links, or other relevant information
